namespace: motadata-apm-agent-np

image:
  repository: motadata2026/motadata-apm-agent
  tag: 8.2.3
  pullPolicy: Always

replicaCount: 1

service:
  type: NodePort
  port: 8181
  nodePort: 30083

env:
  motadataServerUrl: "https://<motadata-ip>:9477/api/v2/rum"
  postIntervalSeconds: "60"
  clusterName: "default"
  deployment: "kubernetes"
